version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map backend port
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Map frontend port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
